[book]
authors = ["bdebruijn"]
language = "en"
multilingual = false
src = "src"
title = "TwinCAT 3 installation"

[output.html]
default-theme = "coal"
git-repository-url = "https://github.com/m-inau/tc3_installation"

[output.html.fold]
enable = true
level = 1
